# Generated by Django 4.0.6 on 2022-09-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_comment_comment_id_comment_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
