# Generated by Django 3.2.8 on 2022-10-21 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='like_user',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
