# Generated by Django 3.2.8 on 2022-11-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20221027_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='write_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
