# Generated by Django 4.1 on 2022-09-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=50)),
                ("content", models.TextField(default="")),
                ("write_time", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
